DROP TABLE IF EXISTS orders CASCADE;
CREATE TABLE orders (
  id SERIAL PRIMARY KEY NOT NULL,
  customer_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  order_date DATE NOT NULL,
  progress VARCHAR(255),
  subtotal INTEGER,
  tax INTEGER
);
